// Toggle-only missions V1 (table enforced).
export const MISSIONS_V1 = [
  // PRIMARY — EASY (1–2)
  {
    id: "P_E1_ROLE_FIRST_TRICK",
    tier: "PRIMARY",
    difficulty: 1,
    tags: ["ROLE", "TRICK"],
    text: "{ROLE:ANY} must win the first trick.",
    check: { kind: "ROLE_WINS_FIRST_TRICK", params: { role: "ANY" } },
    reward: { type: "ASSET", id: "PARK" },
  },
  {
    id: "P_E1_TRICK_RANK_2",
    tier: "PRIMARY",
    difficulty: 1,
    tags: ["RANK", "TRICK"],
    text: "Win a trick with a 2.",
    check: { kind: "TRICK_WON_WITH_RANK", params: { rank: 2 } },
    reward: { type: "ASSET", id: "MARKET" },
  },
  {
    id: "P_E2_ROLE_ANY_DIAMOND",
    tier: "PRIMARY",
    difficulty: 2,
    tags: ["ROLE", "SUIT"],
    text: "{ROLE:ANY} must win at least one trick in ♦.",
    check: { kind: "ROLE_WINS_ANY_TRICK_IN_SUIT", params: { role: "ANY", suit: "D" } },
    reward: { type: "ASSET", id: "MARKET" },
  },
  {
    id: "P_E2_AT_LEAST_3_HEARTS",
    tier: "PRIMARY",
    difficulty: 2,
    tags: ["SUIT", "COUNT"],
    text: "Win at least 3 tricks in ♥.",
    check: { kind: "AT_LEAST_TRICKS_IN_SUIT", params: { suit: "H", n: 3 } },
    reward: { type: "ASSET", id: "PARK" },
  },
  {
    id: "P_E2_EXACT_2_CLUBS",
    tier: "PRIMARY",
    difficulty: 2,
    tags: ["SUIT", "COUNT", "CONTROL"],
    text: "Win exactly 2 tricks in ♣.",
    check: { kind: "EXACT_TRICKS_IN_SUIT", params: { suit: "C", n: 2 } },
    reward: { type: "ASSET", id: "CLINIC" },
  },
  {
    id: "P_E2_NO_ACES",
    tier: "PRIMARY",
    difficulty: 2,
    tags: ["RANK", "RESTRICTION"],
    text: "No trick may be won with an Ace.",
    check: { kind: "NO_TRICKS_WITH_RANK", params: { rank: "A" } },
    reward: { type: "POLICY", id: "ZONING_REFORM" },
  },

  // PRIMARY — MEDIUM (3)
  {
    id: "P_M3_ROLE_LAST_TRICK",
    tier: "PRIMARY",
    difficulty: 3,
    tags: ["ROLE", "TRICK"],
    text: "{ROLE:ANY} must win the last trick.",
    check: { kind: "WIN_LAST_TRICK", params: { role: "ANY" } },
    reward: { type: "ASSET", id: "TRANSIT_STOP" },
  },
  {
    id: "P_M3_EXACT_2_DIAMONDS",
    tier: "PRIMARY",
    difficulty: 3,
    tags: ["SUIT", "COUNT", "CONTROL"],
    text: "Win exactly 2 tricks in ♦.",
    check: { kind: "EXACT_TRICKS_IN_SUIT", params: { suit: "D", n: 2 } },
    reward: { type: "ASSET", id: "MARKET" },
  },
  {
    id: "P_M3_AT_LEAST_4_DIAMONDS",
    tier: "PRIMARY",
    difficulty: 3,
    tags: ["SUIT", "COUNT"],
    text: "Win at least 4 tricks in ♦.",
    check: { kind: "AT_LEAST_TRICKS_IN_SUIT", params: { suit: "D", n: 4 } },
    reward: { type: "POLICY", id: "GRANT_FUNDING" },
  },
  {
    id: "P_M3_TRICK_RANK_3",
    tier: "PRIMARY",
    difficulty: 3,
    tags: ["RANK", "TRICK"],
    text: "Win a trick with a 3.",
    check: { kind: "TRICK_WON_WITH_RANK", params: { rank: 3 } },
    reward: { type: "ASSET", id: "PARK" },
  },
  {
    id: "P_M3_ROLE_TRICK_RANK_2",
    tier: "PRIMARY",
    difficulty: 3,
    tags: ["ROLE", "RANK"],
    text: "{ROLE:ANY} must win a trick with a 2.",
    check: { kind: "ROLE_WINS_TRICK_WITH_RANK", params: { role: "ANY", rank: 2 } },
    reward: { type: "ASSET", id: "CLINIC" },
  },
  {
    id: "P_M3_AT_LEAST_3_SPADES",
    tier: "PRIMARY",
    difficulty: 3,
    tags: ["SUIT", "COUNT"],
    text: "Win at least 3 tricks in ♠.",
    check: { kind: "AT_LEAST_TRICKS_IN_SUIT", params: { suit: "S", n: 3 } },
    reward: { type: "ASSET", id: "CLINIC" },
  },

  // PRIMARY — HARD (4–5)
  {
    id: "P_H4_EXACT_1_HEART",
    tier: "PRIMARY",
    difficulty: 4,
    tags: ["SUIT", "CONTROL"],
    text: "Win exactly 1 trick in ♥.",
    check: { kind: "EXACT_TRICKS_IN_SUIT", params: { suit: "H", n: 1 } },
    reward: { type: "POLICY", id: "GRANT_FUNDING" },
  },
  {
    id: "P_H4_EXACT_1_DIAMOND",
    tier: "PRIMARY",
    difficulty: 4,
    tags: ["SUIT", "CONTROL"],
    text: "Win exactly 1 trick in ♦.",
    check: { kind: "EXACT_TRICKS_IN_SUIT", params: { suit: "D", n: 1 } },
    reward: { type: "POLICY", id: "ZONING_REFORM" },
  },
  {
    id: "P_H4_NO_KINGS",
    tier: "PRIMARY",
    difficulty: 4,
    tags: ["RANK", "RESTRICTION"],
    text: "No trick may be won with a King.",
    check: { kind: "NO_TRICKS_WITH_RANK", params: { rank: "K" } },
    reward: { type: "ASSET", id: "TRANSIT_STOP" },
  },
  {
    id: "P_H5_ROLE_FIRST_AND_LAST",
    tier: "PRIMARY",
    difficulty: 5,
    tags: ["ROLE", "TRICK", "HARD"],
    text: "{ROLE:ANY} must win the first trick and the last trick.",
    check: { kind: "WIN_LAST_TRICK", params: { role: "ANY", plus: "ROLE_WINS_FIRST_TRICK" } },
    reward: { type: "POLICY", id: "GRANT_FUNDING" },
  },
  {
    id: "P_H5_TRICK_RANK_2_AND_3",
    tier: "PRIMARY",
    difficulty: 5,
    tags: ["RANK", "HARD"],
    text: "Win a trick with a 2 and a trick with a 3.",
    check: { kind: "TRICK_WON_WITH_RANK", params: { ranks: [2, 3] } },
    reward: { type: "POLICY", id: "ZONING_REFORM" },
  },

  // OPTIONAL — EASY (1–2)
  {
    id: "O_E1_AT_LEAST_3_CLUBS",
    tier: "OPTIONAL",
    difficulty: 1,
    tags: ["SUIT", "COUNT"],
    text: "Optional: Win at least 3 tricks in ♣.",
    check: { kind: "AT_LEAST_TRICKS_IN_SUIT", params: { suit: "C", n: 3 } },
    reward: { type: "ASSET", id: "CLINIC" },
  },
  {
    id: "O_E1_AT_LEAST_3_DIAMONDS",
    tier: "OPTIONAL",
    difficulty: 1,
    tags: ["SUIT", "COUNT"],
    text: "Optional: Win at least 3 tricks in ♦.",
    check: { kind: "AT_LEAST_TRICKS_IN_SUIT", params: { suit: "D", n: 3 } },
    reward: { type: "ASSET", id: "MARKET" },
  },
  {
    id: "O_E2_EXACT_2_SPADES",
    tier: "OPTIONAL",
    difficulty: 2,
    tags: ["SUIT", "CONTROL"],
    text: "Optional: Win exactly 2 tricks in ♠.",
    check: { kind: "EXACT_TRICKS_IN_SUIT", params: { suit: "S", n: 2 } },
    reward: { type: "ASSET", id: "CLINIC" },
  },
  {
    id: "O_E2_TRICK_RANK_4",
    tier: "OPTIONAL",
    difficulty: 2,
    tags: ["RANK"],
    text: "Optional: Win a trick with a 4.",
    check: { kind: "TRICK_WON_WITH_RANK", params: { rank: 4 } },
    reward: { type: "ASSET", id: "PARK" },
  },
  {
    id: "O_E2_ROLE_ANY_HEART",
    tier: "OPTIONAL",
    difficulty: 2,
    tags: ["ROLE", "SUIT"],
    text: "Optional: {ROLE:ANY} must win at least one trick in ♥.",
    check: { kind: "ROLE_WINS_ANY_TRICK_IN_SUIT", params: { role: "ANY", suit: "H" } },
    reward: { type: "ASSET", id: "PARK" },
  },

  // OPTIONAL — MEDIUM (3)
  {
    id: "O_M3_EXACT_1_CLUB",
    tier: "OPTIONAL",
    difficulty: 3,
    tags: ["SUIT", "CONTROL"],
    text: "Optional: Win exactly 1 trick in ♣.",
    check: { kind: "EXACT_TRICKS_IN_SUIT", params: { suit: "C", n: 1 } },
    reward: { type: "ASSET", id: "TRANSIT_STOP" },
  },
  {
    id: "O_M3_NO_QUEENS",
    tier: "OPTIONAL",
    difficulty: 3,
    tags: ["RANK", "RESTRICTION"],
    text: "Optional: No trick may be won with a Queen.",
    check: { kind: "NO_TRICKS_WITH_RANK", params: { rank: "Q" } },
    reward: { type: "POLICY", id: "ZONING_REFORM" },
  },
  {
    id: "O_M3_ROLE_TRICK_RANK_3",
    tier: "OPTIONAL",
    difficulty: 3,
    tags: ["ROLE", "RANK"],
    text: "Optional: {ROLE:ANY} must win a trick with a 3.",
    check: { kind: "ROLE_WINS_TRICK_WITH_RANK", params: { role: "ANY", rank: 3 } },
    reward: { type: "ASSET", id: "MARKET" },
  },
  {
    id: "O_M3_AT_LEAST_4_HEARTS",
    tier: "OPTIONAL",
    difficulty: 3,
    tags: ["SUIT", "COUNT"],
    text: "Optional: Win at least 4 tricks in ♥.",
    check: { kind: "AT_LEAST_TRICKS_IN_SUIT", params: { suit: "H", n: 4 } },
    reward: { type: "POLICY", id: "GRANT_FUNDING" },
  },

  // OPTIONAL — HARD (4–5)
  {
    id: "O_H4_ROLE_LAST_TRICK",
    tier: "OPTIONAL",
    difficulty: 4,
    tags: ["ROLE", "TRICK"],
    text: "Optional: {ROLE:ANY} must win the last trick.",
    check: { kind: "WIN_LAST_TRICK", params: { role: "ANY" } },
    reward: { type: "ASSET", id: "TRANSIT_STOP" },
  },
  {
    id: "O_H4_NO_JACKS",
    tier: "OPTIONAL",
    difficulty: 4,
    tags: ["RANK", "RESTRICTION"],
    text: "Optional: No trick may be won with a Jack.",
    check: { kind: "NO_TRICKS_WITH_RANK", params: { rank: "J" } },
    reward: { type: "ASSET", id: "CLINIC" },
  },
  {
    id: "O_H5_EXACT_1_DIAMOND",
    tier: "OPTIONAL",
    difficulty: 5,
    tags: ["SUIT", "CONTROL", "HARD"],
    text: "Optional: Win exactly 1 trick in ♦.",
    check: { kind: "EXACT_TRICKS_IN_SUIT", params: { suit: "D", n: 1 } },
    reward: { type: "POLICY", id: "GRANT_FUNDING" },
  },
];
